name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar proyecto
      run: dotnet build --configuration Release

    - name: Publicar proyecto
      run: dotnet publish -c Release -o release

    - name: Desplegar a Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: BirdSing
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: release
