name: Build and Deploy ASP.NET Core to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # ajusta si usas otra versión

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: BirdSing        # <-- Asegúrate de que coincide con el nombre de tu Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE2 }}
          package: ./publish
